### ISSUE TITLE
Overriding the input type ignored

### ISSUE THREAD

**Issue by svossen** [tenon-io/tenon-ui#19]
I’m trying to override the default input type as described in the documentation with:
```
<Form.TextInputController
    name="petAge"
    labelText="Age of pet"
    type="number"
    contentHintText="The pet's name should be longer than three characters"
    component={Input}
/>
```

Yet my input type is still rendered as `text`. I also tried other values like `password` or `tel`, but it keeps rendering as `text`. Other props like `disabled` are correctly passed through.

Looks like the function `getInputProps` explicitly uses `type: 'text'`.

**Comment by AlmeroSteyn** [comment]
Hi @svossen, you are quite right. Internally the `type` is being destructured out in the render function and then gets lost.

We will get to fixing this as soon as possible.

If you are completely stuck for now you can use the long renderfunction version where you need to change the `<input>`  type. It does still work:

```
<Form.TextInputController
    name="petAge"
>
{props => <Input {...props}    
                   labelText="Age of pet"  
                   contentHintText="The pet's name should be longer than three characters"
                   type="number"
/>}
</Form.TextInputController>
```

Thanks for reporting!

**Comment by svossen** [comment]
Thanks for your help! I wasn’t completely stuck but it’s nice to have it working via you’re example.

**Comment by AlmeroSteyn** [comment]
@svossen The issues has been fixed and merged. I hope to do a new release later today somewhere as I want to add a brand new widget as well!

Once again thanks for reporting. Glad you found this.

**Comment by svossen** [comment]
That’s fast. Thanks a lot!

**Comment by AlmeroSteyn** [comment]
@svossen it's a pleasure! Luckily it wasn't a crazy fix.

It's in the new v1.1.0 release :-)

While you are there check out our new disclosure widget! https://tenon-ui.info/disclosure
